VERSION_YEAR = 2021
VERSION_MONTH = int('10')
VERSION_DAY = int('30')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('55')
MAJOR_VERSION = 1
MINOR_VERSION = 2
PATCH_VERSION = 202110301155
version_date = '2021/10/30 11:55'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
