VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('10')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('47')
MAJOR_VERSION = 0
MINOR_VERSION = 8
PATCH_VERSION = 202109102047
version_date = '2021/09/10 20:47'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
